# -*- coding: utf-8 -*-
"""Mini_Project_Kraljic_Matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1io6HW4OARk7TAPYhuyzrLVmFngzKPpap
"""

import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

df = pd.read_csv("/content/realistic_kraljic_dataset.csv")

df

df.columns

df["Kraljic_Category"].unique()

df1 = df.drop(['Product_Name', 'Supplier_Region','Product_ID'], axis=1)

df1

df1.columns

df1["Single_Source_Risk"] = df1["Single_Source_Risk"].map({"Yes":1,"No":0})

df1

x = df1[['Lead_Time_Days', 'Order_Volume_Units', 'Cost_per_Unit',
       'Supply_Risk_Score', 'Profit_Impact_Score', 'Environmental_Impact',
       'Single_Source_Risk']]
y = df1['Kraljic_Category']

knn_model = KNeighborsClassifier()
NB_model  = GaussianNB()
LR_model  = LogisticRegression()
svm_model = SVC()

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2 , random_state=12)

knn_model.fit(x_train,y_train)

NB_model.fit(x_train,y_train)

LR_model.fit(x_train,y_train)

svm_model.fit(x_train,y_train)

y_pred_knn = knn_model.predict(x_test)

y_pred_NB  = NB_model.predict(x_test)

y_pred_LR  = LR_model.predict(x_test)

y_pred_svm = svm_model.predict(x_test)

print(classification_report(y_test, y_pred_knn))

print(classification_report(y_test, y_pred_NB))

print(classification_report(y_test, y_pred_LR))

print(classification_report(y_test, y_pred_svm))

import pickle

with open("NB_model.pkl","wb") as f:
  pickle.dump(NB_model,f)